<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="MSTest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Sushi81.Pos.Domain/Sushi81.Pos.Domain.csproj" />
    <ProjectReference Include="../../src/Sushi81.Pos.Application/Sushi81.Pos.Application.csproj" />
    <ProjectReference Include="../../src/Sushi81.Pos.Infrastructure/Sushi81.Pos.Infrastructure.csproj" />
  </ItemGroup>
</Project>
