<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Sushi81.Pos.Domain/Sushi81.Pos.Domain.csproj" />
  </ItemGroup>
</Project>
